;(()=>{
  if(window.__growthPracticeV57)return;
  window.__growthPracticeV57=true;
  state.practiceSessions=Array.isArray(state.practiceSessions)?state.practiceSessions:[];
  const currentCp=()=>{const cps=state?.journey?.checkpoints||[];return cps.find(c=>c.status==='current')||cps.find(c=>c.status!=='done')||cps[0]||null};
  const actor=()=>state.role==='support'?'Support':state.role==='management'?'Management':'Staff';
  const safe=v=>typeof esc==='function'?esc(String(v??'')):String(v??'');
  const commit=()=>window.GrowthTeam?.commitState?window.GrowthTeam.commitState():typeof save==='function'?save():undefined;
  const modelRows=()=>Array.isArray(state.modelBookings)?state.modelBookings:Array.isArray(state.modelPlans)?state.modelPlans:Array.isArray(state.models)?state.models:[];
  const newDraft=()=>{const cp=currentCp(),today=new Date().toISOString().slice(0,10),rows=modelRows().filter(x=>!x.date||x.date>=today),m=(rows.length?rows:modelRows()).slice().sort((a,b)=>String(a.date||'9999').localeCompare(String(b.date||'9999'))||String(a.time||'').localeCompare(String(b.time||'')))[0]||null;return{step:1,modelId:m?.id||'',modelName:m?.name||m?.modelName||'',menu:m?.menu||'',domain:cp?.domain||'technical',judgmentStage:cp?.judgmentStage||window.GrowthTeamCore?.inferJudgmentStage?.(cp)||'observation',question:m?.validationQuestion||m?.note||state?.currentQuestion?.text||state?.issue?.title||cp?.issue||'',hypothesis:'',plan:'',result:'',win:'',gap:'',next:'',minutes:60,evidenceTitle:''}};
  state.practiceDraft=state.practiceDraft&&typeof state.practiceDraft==='object'?state.practiceDraft:newDraft();
  const prevRender=render;
  const draft=()=>state.practiceDraft;
  function options(){return modelRows().map(m=>`<option value="${safe(m.id||'')}" ${draft().modelId===m.id?'selected':''}>${safe([m.date,m.time,m.name||m.modelName,m.menu].filter(Boolean).join('｜'))}</option>`).join('')}
  function renderPractice(){
    const root=document.getElementById('practice');if(!root||state.page!=='practice')return;
    const cp=currentCp(),d=draft(),step=Math.max(1,Math.min(3,Number(d.step)||1));
    const recent=state.practiceSessions.slice().reverse().slice(0,4);
    root.innerHTML=`
      <div class="practice57-head"><div><div class="eyebrow">PRACTICE WORKSPACE</div><h1>一度に考えるのは、一問だけ。</h1><p class="lead">Current Checkpointの「今回の問い」を、モデル検証からEvidenceへ変換します。</p></div><div class="practice57-context"><span>${safe(cp?`${cp.code||''} ${cp.title||''}`:'Checkpoint未設定')}</span><b>${safe(state?.issue?.title||cp?.issue||'今回の問い未設定')}</b></div></div>
      <div class="practice57-stepper"><button class="${step===1?'active':''}" data-practice-step="1"><i>1</i><span>設計</span></button><em></em><button class="${step===2?'active':''}" data-practice-step="2"><i>2</i><span>記録</span></button><em></em><button class="${step===3?'active':''}" data-practice-step="3"><i>3</i><span>Evidence化</span></button></div>
      <section class="practice57-shell">
        <div class="practice57-main">
          ${step===1?`<div class="practice57-kicker">STEP 1 / DESIGN</div><h2>今日、何を確かめるか。</h2><div class="practice57-form"><label>モデル予定<select id="p57Model"><option value="">予定を選択しない</option>${options()}</select></label><div class="practice57-pair"><label>モデル名<input id="p57ModelName" value="${safe(d.modelName)}" placeholder="モデル名"></label><label>メニュー<input id="p57Menu" value="${safe(d.menu)}" placeholder="カット / カラー"></label></div><label class="practice57-question">今日の一問<textarea id="p57Question" placeholder="何を判断できるようになる必要がある？">${safe(d.question)}</textarea></label><label>仮説<textarea id="p57Hypothesis" placeholder="こう判断すれば完成像に近づくはず">${safe(d.hypothesis)}</textarea></label><label>検証する操作<textarea id="p57Plan" placeholder="基準点、セクション、引き出し、角度など">${safe(d.plan)}</textarea></label></div>`:''}
          ${step===2?`<div class="practice57-kicker">STEP 2 / OBSERVE</div><h2>起きたことと、判断を分ける。</h2><div class="practice57-summary"><span>QUESTION</span><b>${safe(d.question||'未入力')}</b></div><div class="practice57-form"><label>実際に起きたこと<textarea id="p57Result" placeholder="結果を事実として記録する">${safe(d.result)}</textarea></label><label>うまくいった判断<textarea id="p57Win" placeholder="再現したい判断・操作">${safe(d.win)}</textarea></label><label>ズレた判断<textarea id="p57Gap" placeholder="不足ではなく、どこで判断がズレたか">${safe(d.gap)}</textarea></label></div>`:''}
          ${step===3?`<div class="practice57-kicker">STEP 3 / TRANSFER</div><h2>次回にも使える形にする。</h2><div class="practice57-summary"><span>OBSERVATION</span><b>${safe(d.result||'結果未入力')}</b></div><div class="practice57-form"><label>次の検証<textarea id="p57Next" placeholder="次に、どの条件で何を確かめる？">${safe(d.next)}</textarea></label><div class="practice57-pair"><label>Evidence名<input id="p57Evidence" value="${safe(d.evidenceTitle)}" placeholder="例：骨格違いで基準点を検証"></label><label>Practice時間（分）<input id="p57Minutes" type="number" min="0" value="${Number(d.minutes)||0}"></label></div><div class="practice57-check"><div><span>Checkpoint</span><b>${safe(cp?`${cp.code||''} ${cp.title||''}`:'未設定')}</b></div><div><span>Evidence追加</span><b>${cp?'ON':'OFF'}</b></div><div><span>Journey反映</span><b>Evidenceで判断</b></div></div></div>`:''}
          <div class="practice57-actions">${step>1?'<button class="btn secondary" data-practice-action="prev">戻る</button>':'<button class="btn secondary" data-page="planner">Model Planner</button>'}<div></div>${step<3?'<button class="btn primary" data-practice-action="next">次へ</button>':'<button class="btn primary" data-practice-action="complete">Practiceを完了</button>'}</div>
        </div>
        <aside class="practice57-side"><div class="practice57-sideblock"><span class="practice57-label">今回の問い</span><h3>${safe(state?.issue?.title||cp?.issue||'未設定')}</h3><button class="btn secondary" data-page="support" data-support-request="practice">Supportで考える</button></div><div class="practice57-sideblock"><span class="practice57-label">MODEL</span><h3>${safe(d.modelName||'未選択')}</h3><p>${safe(d.menu||'メニュー未設定')}</p></div><div class="practice57-sideblock"><span class="practice57-label">AUTO SAVE</span><p>入力内容はブラウザ内へ保存されます。途中でHomeへ戻っても続きから再開できます。</p></div></aside>
      </section>
      <section class="practice57-recent"><div class="practice57-recenthead"><div><span class="practice57-label">RECENT PRACTICE</span><h2>直近の検証</h2></div></div><div class="practice57-recentgrid">${recent.map(x=>`<article><div><span>${safe(x.at||'')}</span><b>${safe(x.modelName||'モデル未設定')}</b></div><h3>${safe(x.question)}</h3><p>${safe(x.next||x.result)}</p><button class="btn secondary small" data-practice-library="${safe(x.id)}">Library化</button></article>`).join('')||'<div class="practice57-empty">完了したPracticeはまだありません。</div>'}</div></section>`;
  }
  const ids={p57ModelName:'modelName',p57Menu:'menu',p57Question:'question',p57Hypothesis:'hypothesis',p57Plan:'plan',p57Result:'result',p57Win:'win',p57Gap:'gap',p57Next:'next',p57Evidence:'evidenceTitle',p57Minutes:'minutes'};
  function persistInputs(){Object.entries(ids).forEach(([id,key])=>{const el=document.getElementById(id);if(el)draft()[key]=key==='minutes'?Number(el.value)||0:el.value});commit()}
  function complete(){persistInputs();const d=draft(),cp=currentCp();if(!d.question.trim())return alert('今日の一問を入力してください。');if(!d.result.trim())return alert('実際に起きたことを入力してください。');if(!d.next.trim())return alert('次の検証を入力してください。');const at=new Date().toISOString();const domain=cp?.domain||d.domain||'technical',judgmentStage=cp?.judgmentStage||d.judgmentStage||window.GrowthTeamCore?.inferJudgmentStage?.(cp)||'observation';const item={...d,id:'practice-'+Date.now(),checkpointId:cp?.id||'',domain,judgmentStage,by:actor(),at};state.practiceSessions.push(item);state.evidenceRecords=Array.isArray(state.evidenceRecords)?state.evidenceRecords:[];const evidence=window.GrowthTeamCore.normalizeEvidenceRecord({id:'evidence-'+Date.now(),title:d.evidenceTitle||`${d.modelName||'モデル'}｜${d.question}`,checkpointId:cp?.id||'',modelId:d.modelId||'',practiceId:item.id,sourceType:'practice',domain,judgmentStage,fact:d.result,judgment:d.win||d.hypothesis,whySo:[d.hypothesis,d.plan,d.gap].filter(Boolean),soWhat:d.next,nextTest:d.next,journeyImpact:{status:'pending',note:d.gap},createdBy:actor(),createdAt:at},state.evidenceRecords.length,{staffId:state.staffId||'',checkpointId:cp?.id||'',actorName:actor()});state.evidenceRecords.push(evidence);state.journeyUpdates=Array.isArray(state.journeyUpdates)?state.journeyUpdates:[];state.journeyUpdates.push(window.GrowthTeamCore.normalizeJourneyUpdate({evidenceId:evidence.id,checkpointId:cp?.id||'',status:'pending',impact:'review',proposedQuestion:d.next,note:d.gap,createdAt:at,createdBy:actor()},state.journeyUpdates.length));if(cp){cp.evidenceIds=Array.isArray(cp.evidenceIds)?cp.evidenceIds:[];cp.evidenceIds.push(evidence.id);cp.evidenceItems=Array.isArray(cp.evidenceItems)?cp.evidenceItems:[];cp.evidenceItems.push(evidence);cp.history=Array.isArray(cp.history)?cp.history:[];cp.actual=Math.round(((Number(cp.actual)||0)+(Number(d.minutes)||0)/60)*10)/10;cp.history.push({at,by:actor(),action:'Practice完了・Evidence審査待ち',detail:d.question})}state.practiceDraft=newDraft();commit();render();alert('PracticeをEvidenceへ変換しました。EvidenceでJourneyへの反映を確認してください。')}
  function toLibrary(id){const x=state.practiceSessions.find(v=>v.id===id);if(!x)return;const evidence=(state.evidenceRecords||[]).find(v=>v.practiceId===x.id);state.library=Array.isArray(state.library)?state.library:[];state.library.unshift({id:'practice-library-'+Date.now(),title:x.evidenceTitle||`${x.modelName||'モデル'}｜Practice`,tag:'Practice',case:x.result,decision:x.hypothesis||x.win,correction:x.gap,rule:x.win,next:x.next,image:'',modelId:x.modelId||'',modelName:x.modelName||'',checkpointId:x.checkpointId||'',domain:x.domain||'',judgmentStage:x.judgmentStage||'',evidenceIds:evidence?[evidence.id]:[],journeyConnection:{status:x.checkpointId?'connected':'pending',checkpointId:x.checkpointId||'',journeyItemId:''},updatedBy:actor(),updatedAt:typeof now==='function'?now():new Date().toLocaleString('ja-JP'),history:[{at:typeof now==='function'?now():new Date().toLocaleString('ja-JP'),by:actor(),action:'PracticeからLibrary化'}]});if(evidence){evidence.libraryAssetIds=Array.from(new Set([...(evidence.libraryAssetIds||[]),state.library[0].id]))}commit();alert('Libraryへ追加しました。')}
  render=function(){prevRender();renderPractice()};
  document.addEventListener('input',e=>{if(e.target.id in ids){const key=ids[e.target.id];draft()[key]=key==='minutes'?Number(e.target.value)||0:e.target.value;commit()}});
  document.addEventListener('change',e=>{if(e.target.id==='p57Model'){const m=modelRows().find(x=>x.id===e.target.value);draft().modelId=e.target.value;if(m){draft().modelName=m.name||m.modelName||'';draft().menu=m.menu||'';draft().question=m.validationQuestion||m.note||state?.currentQuestion?.text||draft().question}commit();render()} });
  document.addEventListener('click',e=>{const step=e.target.closest('[data-practice-step]');if(step){persistInputs();draft().step=Number(step.dataset.practiceStep);commit();render();return}const action=e.target.closest('[data-practice-action]');if(action){persistInputs();if(action.dataset.practiceAction==='next')draft().step=Math.min(3,(Number(draft().step)||1)+1);if(action.dataset.practiceAction==='prev')draft().step=Math.max(1,(Number(draft().step)||1)-1);commit();if(action.dataset.practiceAction==='complete')complete();else render();return}const lib=e.target.closest('[data-practice-library]');if(lib)toLibrary(lib.dataset.practiceLibrary)});
  render();
})();
